### PR TITLE
updated deploy-docker.sh to docker compose v2

### PR DESCRIPTION
**Pull request by adirola**
The current docker deployment script will not work with docker compose v2 installed and throws an error of unknown command "docker-compose"

Updated the script to docker compose v2

Issue: https://github.com/0xPolygonHermez/zkevm-contracts/issues/128

### CODE REVIEW

**Comment by invocamanman** [comment]
Hi thank you!!!^^

But didin't this PR breaks the compatibility with the previous docker compose version?

**Comment by adirola** [comment]
@invocamanman yes this is a breaking change but most new users from july 2023 will only get docker compose v2. Based on this we can either restrict the docker-compose version in the repo documentation or create new script for version v2 so as to accommodate people using docker compose v2

**Comment by invocamanman** [comment]
This actually seems better! thank you so much!
I think you just have to sign the CLA and that's it ^^

**Comment by invocamanman** [comment]
Also pls correct the file name `docker/scripts/deploy-dockerc2.sh` --> `docker/scripts/deploy-dockerv2.sh` ^^

**Comment by adirola** [comment]
Hey @invocamanman thanks for the guidance, as mentioned in comments i have updated the file name and squashed the commit into single commit

**Comment by invocamanman** [comment]
you should be added to the CLA, try to change a commit name or something to reset it, if not don't let me merge it TT

**Review by invocamanman — APPROVED** [review]

**Comment by adirola** [comment]
Done @invocamanman, i think its good to merge from my end

**Pull request merged**
