### PR TITLE
fix OZ upgradeability filename

### PR DESCRIPTION
**Pull request by bap2pecs**
when using a local geth, the default chain ID is 1337. So the Manifest file is named `unknown-1337.json` instead of `unknown-31337.json`

so `rm -f .openzeppelin/unknown-31337.json` doesn't work.

### CODE REVIEW

**Comment by invocamanman** [comment]
I have some PRs pending, where the new contracts of the V2 is updated, could you done this PR once merged onto develop?¿ ^^
And thank you ^^!

**Comment by bap2pecs** [comment]
@invocamanman for sure, lmk when it's merged

**Comment by invocamanman** [comment]
now is good to go hehe ^^

**Comment by bap2pecs** [comment]
@invocamanman alright. I just changed base branch to `develop`

**Comment by invocamanman** [comment]
Thank yoou!!!

**Pull request merged**
