### PR TITLE
fix: multiple typos

### PR DESCRIPTION
**Pull request by criadoperez**
Corrected multiple typos

### CODE REVIEW

**Comment by Samuel0147** [comment]
Cool

**Review by Samuel0147 — APPROVED** [review]
Cute

**Comment by invocamanman** [comment]
Pleas make a rebase to the current `develop` branch

**Comment by criadoperez** [comment]
> Pleas make a rebase to the current `develop` branch

Done. All changes know based on the current `develop` branch.

**Comment by invocamanman** [comment]
Ty

**Pull request merged**
